<?php

/**
* Implements hook_menu(),
*/

function methos_menu() {
	$items['methos'] = array(
		'title' => 'Cars',
		'page callback' => 'all_cars_page',
		'access arguments' => array('access content'),
	);

	return $items;
}

/**
* hook_theme(),
*/

function methos_theme() {
	return array(
		'all_cars' => array(
			'template' => 'all-cars',
		),
	);
}

/**
* All cars callback
*/

function all_cars_page() {

	drupal_add_library('angularjs', 'angularjs');

	$path = drupal_get_path('module', 'methos');
	drupal_add_js($path . '/js/app.js', array('weight' => 1));
	drupal_add_js($path . '/js/angular-slider.min.js', array('weight' => 1));
	drupal_add_css($path . '/css/car-style.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));
	drupal_add_css($path . '/css/angular-slider.min.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));

	return theme('all_cars');
}